# Generated by Django 6.0.4 on 2026-04-27 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готов'), ('archived', 'Архив'), ('deleted', 'Удален')], default='draft', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_documents', to='catalog.templateversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_key', models.CharField(max_length=120)),
                ('variable_label', models.CharField(blank=True, max_length=180)),
                ('value', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='documents.userdocument')),
            ],
            options={
                'ordering': ['variable_key'],
                'unique_together': {('user_document', 'variable_key')},
            },
        ),
    ]
