# Generated by Django 6.0.5 on 2026-05-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_restrict_domains_and_expand_real_estate_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateversion',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='templates/docx/', verbose_name='Размеченный .docx шаблон'),
        ),
    ]
