# Generated by Django 6.0.5 on 2026-05-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_docx_file_to_templateversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название приложения')),
                ('docx_file', models.FileField(upload_to='templates/docx/attachments/', verbose_name='Файл приложения (.docx)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='catalog.templateversion')),
            ],
            options={
                'verbose_name': 'Приложение к шаблону',
                'verbose_name_plural': 'Приложения к шаблонам',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
